### ISSUE TITLE
Attribute Error during stable-diffusion server installation.

### ISSUE THREAD

**Issue by ThisIsOrangeJuice** [blueturtleai/gimp-stable-diffusion#32]
I am following through the local install guide and when I run this command:
`cog run script/download-weights <your huggingface token>` 
with my token from huggingface, its throws this error:
`AttributeError: module transformers has no attribute CLIPImageProcessor`

Here is a little more if it is any help:
`Traceback (most recent call last):
 File "/src/script/download-weights", line 12, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 500, in from_pretrained
    class_obj = getattr(library, class_name)
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 995, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute CLIPImageProcessor
ⅹ exit status 1`

Any ideas?

Edit: Realized I forgot to mention I am on Windows 11 using WSL.

**Comment by blueturtleai** [comment]
Unfortunately, I don’t know what this error caused. Cog is an external repository, which I use. You could try to open an issue here: https://github.com/replicate/cog-stable-diffusion

I forked the cog repository some time ago, so it’s possible, that this error occurs, because my fork isn’t up to date. But updating could cause additional problems.

So, under the bottom line I think I should probably better deprecate my Gimp local plugin, as I can’t support it any longer.

**Comment by blueturtleai** [comment]
As i didn’t hear from you for some days, I close this issue.

**Comment by blueturtleai** [comment]
I moved the source for the local version now to discontinued/local, as I'm unfortunately no longer able to support it.
